### ISSUE TITLE
OpenVPN AMIs should be hardened

### ISSUE THREAD

**Issue by dav3r** [cisagov/openvpn-packer#24]
# 🚀 Feature Proposal

The OpenVPN AMIs should have the ability to be hardened.

## Motivation

In the COOL, the OpenVPN instance(s) are part of the static environment and therefore must be hardened.

## Pitch

Ideally the Packer playbook would apply a hardening Ansible role at the end of the AMI building process.

## Remaining items
- [ ] Ensure permissions on bootloader config are configured
- [x] Disable USB Storage - modprobe
- [x] Ensure AIDE is installed
- [x] Ensure filesystem integrity is regularly checked
- [x] Ensure authentication required for single user mode
- [x] Ensure AppArmor is enabled in the bootloader configuration
- [x] Ensure systemd-timesyncd/chrony is configured
- [x] Ensure LDAP client is not installed
- [x] Ensure packet redirect sending is disabled
- [x] Ensure source routed packets are not accepted
- [x] Ensure IPv6 default deny firewall policy
- [x] Ensure IPv4/IPv6 loopback traffic is configured
- [x] Ensure logging is configured
- [x] Ensure permissions on all logfiles are configured
- [x] Ensure password reuse is limited
- [x] Ensure system accounts are secured and non-login
- [x] Ensure root PATH Integrity
- [x] Ensure users' home directories permissions are 750 or more restrictive

**Comment by jsf9k** [comment]
See [this branch in cisagov/openvpn-packer](https://github.com/cisagov/openvpn-packer/tree/feature/hardening) and [cisagov/ansible-role-hardening](https://github.com/cisagov/ansible-role-hardening).

**Comment by dav3r** [comment]
Hardening guide: [CIS_Debian_Linux_10_Benchmark_v1.0.0.pdf](https://app.zenhub.com/files/192398352/75a259af-042c-443a-bcdc-671ff371009b/download)

**Comment by dav3r** [comment]
@jsf9k has created this draft PR:  https://github.com/cisagov/openvpn-packer/pull/27

**Comment by jsf9k** [comment]
The initial hardening PR was merged some time ago.  I'd like to close this issue and just create new issues if any new details come up, but the bootloader config permissions issue is still unresolved.
