### ISSUE TITLE
Can no longer connect to VPN after EC2 instance is "stopped" and then "started"

### ISSUE THREAD

**Issue by jsf9k** [cisagov/openvpn-packer#26]
# 🐛 Bug Report

If I start with a working OpenVPN EC2 instance based on the AMI created from this repository, then "stop" and "start" the instance in the AWS console, I can no longer connect to the VPN.

## To Reproduce

- Start with a working OpenVPN EC2 instance based on the AMI created from this repository.
- Go to the AWS console and "stop" the instance.
- Wait for the AWS console to report that the instance has been "stopped".
- "Start" the instance in the AWS console.
- Wait for the AWS console to report that the instance is "running" and attempt to connect to the VPN.

## Expected behavior

I should be able to connect to the VPN after the underlying EC2 instance is "stopped" and then "started".

## Any helpful log output

When the VPN is in the borked state and I try to connect I see the following and then it appears to hang:

```console
$ connect_to_cool_staging_vpn.sh 
Thu Aug 27 12:16:41 2020 OpenVPN 2.5_git [git:master/6ccb3b2e3ae84193+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 23 2019
Thu Aug 27 12:16:41 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Thu Aug 27 12:16:41 2020 PKCS#11: Adding PKCS#11 provider '/usr/lib/pkcs11/opensc-pkcs11.so'
Thu Aug 27 12:16:44 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Aug 27 12:16:44 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]3.236.137.139:1194
Thu Aug 27 12:16:44 2020 UDP link local: (not bound)
Thu Aug 27 12:16:44 2020 UDP link remote: [AF_INET]3.236.137.139:1194
```

**Comment by dav3r** [comment]
It turns out that our OpenVPN instance doesn't have an Elastic IP, so when we stopped/started the instance, it came back with a different public IP address, which is no longer the IP that `vpn.staging.cool.cyber.dhs.gov` resolves to, hence the problem that we were seeing.  

When I manually changed the DNS entry to point to the new public IP address, I was able to successfully connect to the Staging VPN.

**Comment by dav3r** [comment]
This should be resolved now thanks to https://github.com/cisagov/openvpn-server-tf-module/pull/42 and https://github.com/cisagov/openvpn-server-tf-module/pull/43.  @jsf9k - please close this issue if you are in agreement.

**Comment by jsf9k** [comment]
I am in agreement.

**Comment by IBatuu** [comment]
> It turns out that our OpenVPN instance doesn't have an Elastic IP, so when we stopped/started the instance, it came back with a different public IP address, which is no longer the IP that `vpn.staging.cool.cyber.dhs.gov` resolves to, hence the problem that we were seeing.
> 
> When I manually changed the DNS entry to point to the new public IP address, I was able to successfully connect to the Staging VPN.

Hey there, I'm having the same problem, how can I manually change the DNS entry to point to the new public IP address, could you provide some guidance please.

**Comment by hassanshamshir** [comment]
@dav3r I have attached the EIP IP but yet facing this issue in OpenVPN community edition.

**Comment by hassanshamshir** [comment]
![image](https://github.com/cisagov/openvpn-packer/assets/45597637/a0b482db-79de-45c2-9005-0cc6eac13420)

**Comment by hassanshamshir** [comment]
@dav3r 
![image](https://github.com/cisagov/openvpn-packer/assets/45597637/4a1c110d-6b5d-4eaf-979c-beb9e6fc2c3b)
